title: Actividades
logo: 
description: Docente: Juan David Martínez Vargas <br> Escuela: Ciencias Aplicadas e Ingeniería <br>Área: Computación y Analítica
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
